name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      sdk_git_ref:
        type: string
        description: "Which git ref of the app to build"

concurrency:
  group: build-android-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk:
    name: "Demo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sdk_git_ref || github.ref }}

      - name: "Install Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build demo app
        run: ./gradlew :rtvi-basic-demo:assembleDebug

      - name: Upload demo APK
        uses: actions/upload-artifact@v4
        with:
          name: Demo App (Debug)
          path: rtvi-basic-demo/build/outputs/apk/debug/rtvi-basic-demo-debug.apk
